import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const P=[
{id:'full',name:'Full Body',ar:'كامل الجسم',days:3,img:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{id:'upper',name:'Upper / Lower',ar:'الجزء العلوي / السفلي',days:4,img:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80'},
{id:'ppl3',name:'Push / Pull / Legs',ar:'3 أيام',days:3,img:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'},
{id:'ppl6',name:'Push / Pull / Legs',ar:'6 أيام',days:6,img:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80'},
{id:'arnold',name:'Arnold Split',ar:'تجزئة أرنولد',days:6,img:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80'},
{id:'phul',name:'PHUL',ar:'قوة + كتلة عضلية',days:4,img:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=80'},
{id:'phat',name:'PHAT',ar:'قوة + هايبرتروفي',days:5,img:'https://images.unsplash.com/photo-1599058917212-d750089bc07f?auto=format&fit=crop&w=900&q=80'}];
const E={push:['Bench Press','Incline Dumbbell Press','Shoulder Press','Lateral Raise','Triceps Pushdown'],pull:['Barbell Row','Lat Pulldown','Seated Cable Row','Face Pull','Biceps Curl'],legs:['Back Squat','Romanian Deadlift','Leg Press','Leg Curl','Calf Raise'],full:['Squat','Bench Press','Lat Pulldown','Romanian Deadlift','Shoulder Press']};
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function App(){const[f,setF]=useState({age:22,weight:75,height:180,sex:'male',goal:'muscle',level:'beginner',days:4}),[sel,setSel]=useState('auto'),[day,setDay]=useState(0);const prog=useMemo(()=>sel!=='auto'?P.find(x=>x.id===sel):f.level==='beginner'?P[0]:+f.days===5?P[6]:+f.days===6?P[3]:P[1],[sel,f.level,f.days]);const bmr=Math.round(10*f.weight+6.25*f.height-5*f.age+(f.sex==='male'?5:-161)),cal=Math.round(bmr*(f.goal==='fat'?1.35:f.goal==='strength'?1.6:1.5)),protein=Math.round(f.weight*(f.goal==='fat'?2:f.goal==='strength'?1.8:1.7));const split=prog.id==='full'?['Full Body']:prog.id==='upper'?['Upper','Lower']:prog.id.includes('ppl')?['Push','Pull','Legs']:prog.id==='arnold'?['Chest + Back','Shoulders + Arms','Legs']:['Upper Power','Lower Power','Upper Hypertrophy','Lower Hypertrophy'];const dn=split[day%split.length],ex=prog.id==='full'?E.full:/push|chest/i.test(dn)?E.push:/pull|back/i.test(dn)?E.pull:E.legs;const u=(k,v)=>{setSel('auto');setDay(0);setF(x=>({...x,[k]:v}))};return <div className="app"><nav className="nav shell"><div className="brand"><div className="brand-mark">▰▰</div><div><strong>GYMLAB</strong><span>TRAIN SMARTER</span></div></div><div className="nav-links"><a className="active">الرئيسية</a><a>برامج التدريب</a><a>قاعدة التمارين</a><a>حاسبات رياضية</a><a>مقالات</a><a>عن الموقع</a></div><div className="nav-actions"><button className="ghost">تسجيل الدخول</button><button className="gold">إنشاء حساب 👤</button></div></nav>
<main><section className="hero shell"><div className="hero-copy"><div className="eyebrow">أكثر من مجرد جيم</div><h1>برنامجك المثالي<br/><em>يبدأ من هنا</em></h1><p>GymLab يساعدك تبني روتينك بثقة، من خلال برامج تدريبية مخصصة وحاسبات دقيقة ومصادر علمية موثوقة.</p><div className="hero-actions"><button className="gold big">ابدأ الآن ←</button><button className="outline big">تعرف على الموقع ◉</button></div><div className="hero-stats"><div><b>+500</b><span>تمرين موثق</span></div><div><b>+20</b><span>برنامج تدريبي</span></div><div><b>+10K</b><span>مستخدم</span></div></div></div><div className="hero-image"><div className="quote-card">التقدم لا يأتي من الحظ<br/><strong>بل من الالتزام.</strong></div></div></section>
<section className="benefits shell">{[['🛡','محتوى موثوق','مبني على مصادر علمية'],['⚙','قاعدة تمارين شاملة','مع شرح وصور ورسوم متحركة'],['▣','حاسبات متقدمة','TDEE, 1RM, BMR وغيرها'],['⌕','برامج متنوعة','للأهداف والمستويات المختلفة']].map(x=><div className="benefit" key={x[1]}><div className="benefit-icon">{x[0]}</div><div><b>{x[1]}</b><span>{x[2]}</span></div></div>)}</section>
<section className="builder shell"><div className="section-head"><div><h2>أنشئ برنامجك التدريبي الآن</h2><p>أدخل معلوماتك واحصل على برنامج مخصص لك خلال ثوانٍ.</p></div><button className="outline small">✦ اختبار تلقائي</button></div><div className="form-grid"><Field label="الهدف الرئيسي"><select value={f.goal} onChange={e=>u('goal',e.target.value)}><option value="muscle">بناء العضلات</option><option value="fat">خسارة الدهون</option><option value="strength">القوة</option><option value="fitness">اللياقة</option></select></Field><Field label="مستوى الخبرة"><select value={f.level} onChange={e=>u('level',e.target.value)}><option value="beginner">مبتدئ</option><option value="intermediate">متوسط</option><option value="advanced">متقدم</option></select></Field><Field label="عدد أيام التدريب"><select value={f.days} onChange={e=>u('days',+e.target.value)}>{[2,3,4,5,6].map(n=><option key={n} value={n}>{n} أيام</option>)}</select></Field><Field label="الجنس"><select value={f.sex} onChange={e=>u('sex',e.target.value)}><option value="male">ذكر</option><option value="female">أنثى</option></select></Field><Field label="العمر"><input type="number" value={f.age} onChange={e=>u('age',+e.target.value)}/></Field><Field label="الطول (سم)"><input type="number" value={f.height} onChange={e=>u('height',+e.target.value)}/></Field><Field label="الوزن (كجم)"><input type="number" value={f.weight} onChange={e=>u('weight',+e.target.value)}/></Field></div><button className="gold generate">إنشاء البرنامج ◎</button></section>
<section className="programs shell"><div className="section-title"><h2>برامج تدريبية جاهزة</h2><p>اختر من أشهر الأنظمة التدريبية المبنية علميًا.</p></div><div className="program-grid">{P.map(p=><button key={p.id} className={'program-card '+(prog.id===p.id?'selected':'')} onClick={()=>{setSel(p.id);setDay(0)}}><img src={p.img}/><div className="program-overlay"><strong>{p.name}</strong><span>{p.ar}</span><small>{p.days} أيام بالأسبوع ›</small></div></button>)}</div></section>
<section className="app-section shell"><div className="phone"><div className="phone-screen"><div className="phone-top">‹ <span>{dn}</span> ×</div>{ex.map((e,i)=><div className="phone-row" key={e}><span>{e}</span><b>{i%2?'3 × 10–12':'4 × 8–10'}</b></div>)}</div></div><div className="app-copy"><span>GYMLAB APP</span><h2>تجربتك أصبحت أسهل</h2><p>احصل على برامجك، تابع تقدمك، وسجل تمارينك من أي مكان.</p><div className="stores"><span>▶ Google Play</span><span> App Store</span></div><small>قريبًا على iOS</small></div><div className="testimonial">“<br/><span>العادات الصغيرة تصنع النتائج الكبيرة.</span></div></section>
<section className="workout shell"><div className="workout-top"><div><h2>{prog.name}</h2><p>مقترح لك: {protein}غ بروتين • {cal.toLocaleString()} سعرة تقريبية</p></div><div className="metrics"><span>BMI <b>{(f.weight/((f.height/100)**2)).toFixed(1)}</b></span><span>البروتين <b>{protein}غ</b></span><span>السعرات <b>{cal.toLocaleString()}</b></span></div></div><div className="day-tabs">{Array.from({length:Math.min(prog.days,6)},(_,i)=><button className={i===day?'active':''} key={i} onClick={()=>setDay(i)}>اليوم {i+1}<small>{split[i%split.length]}</small></button>)}</div><div className="exercise-list">{ex.map((e,i)=><div className="exercise" key={e}><div><b>{e}</b><span>{i?'تمرين مساعد':'تمرين مركب • أساسي'}</span></div><strong>{f.goal==='strength'?'4 × 5–8':'3 × 8–12'}</strong><button>▶</button></div>)}</div></section></main>
<footer className="footer"><div className="shell footer-inner"><div className="brand footer-brand"><div className="brand-mark">▰▰</div><div><strong>GYMLAB</strong><span>TRAIN SMARTER</span></div><p>جسم أقوى · حياة أفضل</p></div><div><b>روابط سريعة</b><a>الرئيسية</a><a>برامج التدريب</a><a>حاسبات رياضية</a><a>عن الموقع</a></div><div><b>مساعدة</b><a>الأسئلة الشائعة</a><a>تواصل معنا</a><a>سياسة الخصوصية</a><a>شروط الاستخدام</a></div><div className="social">◎ ◉ ♪ 𝕏<br/><small>© 2026 GymLab. جميع الحقوق محفوظة.</small></div></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);